export const ADD_PLAYER = 'ADD_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const SET_NAME = 'SET_NAME';

export const CONNECTING_TO_SERVER = 'CONNECTING_TO_SERVER';
export const CONNECTED_TO_SERVER = 'CONNECTED_TO_SERVER';
export const DISCONNECTED_FROM_SERVER = 'DISCONNECTED_FROM_SERVER';
export const JOIN_SERVER = 'JOIN_SERVER';
export const CONNECTION_ACK = 'CONNECTION_ACK';
