export const ADD_PLAYER = 'ADD_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const SET_NAME = 'SET_NAME';

export const CONNECTING_TO_SERVER = 'CONNECTING_TO_SERVER';
export const CONNECTED_TO_SERVER = 'CONNECTED_TO_SERVER';
export const DISCONNECTED_FROM_SERVER = 'DISCONNECTED_FROM_SERVER';
export const JOIN_SERVER = 'JOIN_SERVER';
export const CONNECTION_ACK = 'CONNECTION_ACK';
export const LEAVE_SERVER = 'LEAVE_SERVER';
export const PLAYER_UPDATE = 'PLAYER_UPDATE';

export const WINDOW_RESIZE = 'WINDOW_RESIZE';
export const WINDOW_ANIMATE = 'WINDOW_ANIMATE';
export const KEY_UP = 'KEY_UP';
export const KEY_DOWN = 'KEY_DOWN';
